### ISSUE TITLE
World Tooltips mod 

### ISSUE THREAD

**Issue by EternalOne11** [mezz/ModNameTooltip#11]
When this mod is downloaded the item description name appears twice when the item is on the ground and looked at with world tooltips.

https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip
https://www.curseforge.com/minecraft/mc-mods/world-tooltips

**Comment by EternalOne11** [comment]
![2019-08-19_11 47 51](https://user-images.githubusercontent.com/42950385/63279653-5eddc600-c277-11e9-8521-71186ce7fb35.png)

**Comment by mezz** [comment]
Thanks for the report!

ModNameTooltip checks that the mod name is not already added, so that it doesn't cause duplicates. I think that World Tooltips is adding the mod name after ModNameTooltip, which I can't prevent.

Please report this to World Tooltips and link back here so we can work together on a solution.
ModNameTooltip is open source (MIT) and they are welcome to reuse my code to prevent duplicates too.
https://github.com/mezz/ModNameTooltip/blob/77ae28c6aa4a1cab24c0cf0c8a44d4f47fb6be54/src/main/java/mezz/modnametooltip/TooltipEventHandler.java#L51-L59

**Comment by EternalOne11** [comment]
World tooltips is fixing this problem in the next version after I reported it to them.
