### ISSUE TITLE
[1.12.2] Option to load after Crafttweaker

### ISSUE THREAD

**Issue by IronPiston** [mezz/ModNameTooltip#8]
Is it possible to have the mod tooltips load after Crafttweaker, so that any tooltips added via scripting can display above the mod name itself?

**Comment by Remyrios** [comment]
Any comment on this @mezz?

**Comment by mezz** [comment]
ModNameTooltip already subscribes to the tooltip even with `LOW` priority so that other mods can put their information first:
https://github.com/mezz/ModNameTooltip/blob/094ab21b5fccf42beb0bf9d19a114e7e3f2fa99a/src/main/java/mezz/modnametooltip/TooltipEventHandler.java#L17

Crafttweaker may also be using `LOW` priority, I'm not sure.
@jaredlll08 do you know more about this issue?

**Comment by jaredlll08** [comment]
No idea why I never got notified about this at the time.

It may be too late, but anyway... 

The tooltip functionality was very primitive in 1.12, we were probably using lowest because some people would want to remove *everything*, including tooltips added in low. 

If it is worth anything, it is much better now in 1.16 so this wouldn't be an issue on new versions.

**Comment by mezz** [comment]
Thanks for the info Jared!
